### PR TITLE
Full parsing of METAR/TAF weather phenomenon descriptions

### PR DESCRIPTION
**Pull request by redfawks**
My first pull request on GitHub™ :)

Hi there, dmbaturin!

Some time ago I was looking for a METAR/TAF library for python and I stumbled across your pytaf project. I really liked the design of it - it was simple and not bloated like others are, yet it's modular and pretty easy to understand. Thanks for the great job so far!

Mostly I was interested in the weather string of METARs and TAFs and I wasn't pleased with the results the library returned. Sometimes some parts were left out and sometimes the grammar was kind of strange, so I took my own try to fix that issue. I hope I can contribute to your project so here's my try.

Here's what I've changed:

*lib/pytaf/taf.py*
* All changes were only made in _parse_weather_phenomena()
* A METAR/TAF weather string can contain up to 3 intensity descr., modifiers and phen. descr., so instead of just looking for only 1 element of each group, the function can now fetch every element of the string. No parts are left out.
* Originally the function returned a list of dictionaries, one dict. per weather string, each element containing none or 1 string. Now every element in the dictonary contains another list, containing up to 3 elements of the intensity, modifier and phen. descriptor.

*lib/pytaf/tafdecoder.py*
* All changes were only made in _decode_weather()
* Instead of using an *elif* construction, a dictionary is now used to translate the abbreviations.
* The returned human readable output is now set together in 6 parts:

    intensities_pre + modifiers_pre + phenomenons_pre + phenomenons_post + modifiers_post + intensities_post

  This way of constructing the output makes it easier to fix strange grammar.
* If there are multiple weather strings in one TAF group they are separated by a '/'

Alright, that's it so far. I hope I didn't screw up - I still have to learn a lot about git. It's a kind of new world to me.
And, of course, any advice is always appreciated.

Thank you!

### CODE REVIEW

**Comment by dmbaturin** [comment]
>it was simple and not bloated like others are
Wait, are there any other publicly available METAR/TAF libraries? At least at the time there apparently weren't any, that's why I started this one.

>sometimes some parts were left out and sometimes the grammar was kind of strange
It was originally written for my friends in the US, so US format, which is incidentally the most predictable was primary focus, and for EU formats I only made attempts to parse the most common ones correctly. My hope was that people who need more complete support will show up and make patches, which, fortunately, did happen!
And strange grammar, yes, sometimes I took shortcuts to make it good enough for most cases without losing my sanity. Getting that thing to work was a lot more demanding than it seemed in the beginning. ;)

Looks good to me so far, I'll merge and do some tests. It would be nice to add unit tests so it's easier to see if a change broke something or not.

**Comment by redfawks** [comment]
> Wait, are there any other publicly available METAR/TAF libraries? At least at the time there apparently weren't any, that's why I started this one.

Whoops, sorry. Don't get me wrong. There do exist other METAR libs for python, like *python-metar* or *pymetar*, but your library is the first and still the only one I found for parsing TAF reports with python so far.
As the parsing of METAR and TAF reports doesn't differ that much I was just looking for any METAR/TAF lib I could find and pytaf was the one I liked the most. I'm already thinking about forking your project to set the focus on parsing METARs based on your code because, as I mentioned before, the way how it works is the most attractive way to me and I'm still in the need for a good METAR lib. Shouln't be that much of work as pytaf is already able to parse most of the information provided by a METAR report.
> Looks good to me so far, I'll merge and do some tests. It would be nice to add unit tests so it's easier to see if a change broke something or not.

Great, thank you! :)
I've already tested the changes by parsing the TAF reports from my local airport for 2 weeks now and the output was always as expected and without grammar issues. I also wrote a little python script to generate some kind of weird but still possible weather phenomenon descriptions like '+REVCSHBCFZSNIC' and the output was still alright so far. I had no issues with realistic weather phen. descriptions but I'll continue testing those weird ones.

**Comment by dmbaturin** [comment]
Oh, I remember now. pymetar doesn't parse anything and queries (rather, scrapes) a website, which is why I didn't even consider it. python-metar is an actual parser it seems, but I didn't know about it for some reason (or maybe I didn't like it and forgot about it, not sure).

I think it may be feasible to parse TAFs by extracting the weather strings and running it through a METAR parser, this would be a reasonable way to combine both in the same library.
I'd happily merge it, if this is your concern, I don't think it's much of a scope creep that warrants a fork. If you want to fork for other reasons, then go ahead and do it of course, that's free software after all. :)

Also, it should be possible to make a grammar for my other project: http://github.com/dmbaturin/cfgen/ that could produce realistic weather strings possibly, and then use it for visual tests.

**Comment by redfawks** [comment]
> I think it may be feasible to parse TAFs by extracting the weather strings and running it through a METAR parser, this would be a reasonable way to combine both in the same library.
I'd happily merge it, if this is your concern, I don't think it's much of a scope creep that warrants a fork.

Yeah I wasn't sure about that but I guess you're right. I'm not a big fan of forking, too. People should concentrate on *one* project, not multiple projects of the same kind where each one has a small feature more or less. So if you say it's alright to get your pytaf to also parse METARs, then it's what I'm going to try next. Guess it'll make it a great allrounder for parsing aviation weather annoucements.
> Also, it should be possible to make a grammar for my other project: http://github.com/dmbaturin/cfgen/ that could produce realistic weather strings possibly, and then use it for visual tests.

Seems interesting! I'll have a closer look at it soon.

**Comment by dmbaturin** [comment]
We could probably avoid making incompatible API changes even, by adding a METAR class, and then dispatching different decode methods depending on object type, either by checking isinstance() or through double dispatch.
The thing I would change is that decode() should have been a classmethod really, having to initialize the decoder with a TAF object was not a bright idea, in retrospect. Maybe we can find some workaround for it, but even if we stick with the current API we still can extend it to handle METAR.

In other news, I made a pypi release today, 1.1.1. Tested installation on a clean machine, works perfectly it seems.

How are you using this library, by the way?
The story beehind the library is pretty silly, my friend and I wanted to add a TAF fetching command to an IRC bot, but we also wanted it to provide decoded version for people who don't know how to read it and we thought we could use some library for it, but then discovered that no such library exists and ended up making one. ;)

**Comment by redfawks** [comment]
> We could probably avoid making incompatible API changes even, by adding a METAR class, and then dispatching different decode methods depending on object type, either by checking isinstance() or through double dispatch.
The thing I would change is that decode() should have been a classmethod really, having to initialize the decoder with a TAF object was not a bright idea, in retrospect. Maybe we can find some workaround for it, but even if we stick with the current API we still can extend it to handle METAR.

Sorry, gotta have a closer look at the code first but I totally agree with you. Let's keep the changes to the API as small as possible. I'll get back to that topic very soon, I promise ;)
> In other news, I made a pypi release today, 1.1.1. Tested installation on a clean machine, works perfectly it seems.

Wow, that's some great news! Very happy to see that I could help! :)
> How are you using this library, by the way?

I'm cycling to work the whole year so it's important for me to know how the weather will be like each day. I'm using a mix of the forecast a hobby meteorologist from my home town issues every two days and the TAF report from my local airport. With that mix of two forecasts I'm perfectly prepared to get to work in a dry condition without being surprised by bad weather.
Atm I'm just using pytaf to get a clean and easy readable TAF forecast, but I'm also planning to use it for widgets (Conky or awesome wm). Just some fooling around with eyecandy and stuff but I'm having a lot of fun with that.
And, well, I don't know jack about meteorology but weather and aviation are two topics that kinda fascinate me thus the project is something I really enjoy working on.

**Comment by redfawks** [comment]
I forgot to mention that I'm more interested in the parser than the decoder. Understanding a TAF/METAR is not that hard if you read it on a daily basis. I need pytaf to provide the parsed information to other scripts, like widgets.
Nevertheless it's also important to keep the decoder up to date, of course :) I won't miss that.

**Comment by dmbaturin** [comment]
Ah, looks like a great use for it indeed.

Yes, that was exactly my motivation for keeping the parser and decoder separate. The IRC bot simply uses slightly different grouping and longer lines to avoid sending too many messages; but I could imagine people redefine the interpretation completely.
Ironically, my own city's airport doesn't make its TAFs available online. "Cobbler's kids run barefoot", or whatever that proverb was. ;)

**Pull request merged**
